export const PAYFAST_ITN_LOG_STORE = Symbol("PAYFAST_ITN_LOG_STORE");
export const PAYFAST_MERCHANT_ID = Symbol("PAYFAST_MERCHANT_ID");
export const PAYFAST_MERCHANT_KEY = Symbol("PAYFAST_MERCHANT_KEY");
export const PAYFAST_PASSPHRASE = Symbol("PAYFAST_PASSPHRASE");
export const PAYFAST_SANDBOX = Symbol("PAYFAST_SANDBOX");
